### PR TITLE
GitHub issue template

### PR DESCRIPTION
**Pull request by pp2amd6**

### CODE REVIEW

**Comment by Ekaterina1994** [comment]
Why do we need this?

**Comment by pp2amd6** [comment]
> Why do we need this?

The template defines the layout for the report: presets blocks, specifies labels.

A single report template reduces the time for creating a report, because the necessary mandatory blocks for a bug report are ready. The template brings bug reports to a single form, which simplifies working with them, regardless of who created it or who will fix it.

As a tester, I won’t need to specify the required attributes of a bug report over and over again, because... this will already be written down.

When creating a report, the user can also choose not to use a template.

**Comment by tritonJS826** [comment]
Lets discuss it together)

**Review by tritonJS826 — CHANGES_REQUESTED** [review]
too much changes. Please recheck

**Comment by pp2amd6** [comment]
Changed in https://github.com/tritonJS826/masters-way/pull/722

**Pull request closed without merging**
